[package]
name = "rumple"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = { version = "0.2.19", default-features = false }
rand = { version = "0.8.5", default-features = false }

[features]
default = ["std"]
std = []
